const PROGRAM={"Upper Strength": [{"name": "Bench Press", "sets": 5, "min": 5, "max": 5, "step": 5}, {"name": "Weighted Pull-Ups", "sets": 5, "min": 5, "max": 5, "step": 5}, {"name": "Standing OHP", "sets": 4, "min": 5, "max": 5, "step": 5}, {"name": "Barbell Row", "sets": 4, "min": 8, "max": 8, "step": 5}, {"name": "Dips", "sets": 4, "min": 8, "max": 8, "step": 5}, {"name": "Hammer Curl", "sets": 3, "min": 10, "max": 10, "step": 5}], "Lower Strength": [{"name": "Back Squat", "sets": 5, "min": 5, "max": 5, "step": 10}, {"name": "Deadlift", "sets": 3, "min": 5, "max": 5, "step": 10}, {"name": "Bulgarian Split Squat", "sets": 3, "min": 8, "max": 8, "step": 5}, {"name": "Leg Curl", "sets": 3, "min": 10, "max": 10, "step": 5}, {"name": "Pinky Crushers", "sets": 3, "min": 12, "max": 12, "step": 5}, {"name": "Weighted Back Extension", "sets": 3, "min": 12, "max": 12, "step": 5}], "Upper Volume": [{"name": "Incline DB Bench", "sets": 5, "min": 10, "max": 10, "step": 5}, {"name": "Chest Supported Row", "sets": 4, "min": 10, "max": 10, "step": 5}, {"name": "Seated DB Press", "sets": 4, "min": 10, "max": 10, "step": 5}, {"name": "Lat Pulldown", "sets": 3, "min": 12, "max": 12, "step": 5}, {"name": "Lateral Raise", "sets": 4, "min": 15, "max": 15, "step": 5}, {"name": "Triceps Pushdown", "sets": 3, "min": 15, "max": 15, "step": 5}, {"name": "EZ Bar Curl", "sets": 3, "min": 12, "max": 12, "step": 5}], "Lower Volume": [{"name": "Front Squat", "sets": 4, "min": 8, "max": 8, "step": 10}, {"name": "Romanian Deadlift", "sets": 4, "min": 8, "max": 8, "step": 10}, {"name": "Leg Extension", "sets": 4, "min": 15, "max": 15, "step": 5}, {"name": "Leg Press", "sets": 3, "min": 15, "max": 15, "step": 10}, {"name": "Calf Raise", "sets": 4, "min": 15, "max": 15, "step": 5}, {"name": "Ab Wheel", "sets": 4, "min": 10, "max": 10, "step": 0}]};
const STORE='seanStrengthTrackerV6_1';
let raw=localStorage.getItem(STORE)||localStorage.getItem('seanStrengthTrackerV6')||localStorage.getItem('seanStrengthTrackerV5')||localStorage.getItem('seanStrengthTrackerV4')||localStorage.getItem('seanStrengthTrackerV2')||localStorage.getItem('seanStrengthTrackerV1');
const state={selected:null,data:raw?JSON.parse(raw):{history:[],startDate:null}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function persist(){localStorage.setItem(STORE,JSON.stringify(state.data));}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function showView(n){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+n+'View').classList.add('active');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===n));if(n==='history')renderHistory();scrollTo(0,0)}
function validDateString(value){return /^\d{4}-\d{2}-\d{2}$/.test(value||'')&&!Number.isNaN(new Date(value+'T00:00:00').getTime())}
function programStartDate(){const dates=(state.data.history||[]).map(w=>w.date).filter(validDateString).sort();return dates[0]||null}
function weekForDate(value){const start=programStartDate();if(!start||!validDateString(value))return 1;const startDate=new Date(start+'T00:00:00'),target=new Date(value+'T00:00:00');const days=Math.floor((target-startDate)/86400000);return Math.max(1,Math.floor(days/7)+1)}
function currentProgramWeek(){return weekForDate(new Date().toISOString().slice(0,10))}
function weekLabel(week){return `Week ${week}${[6,12].includes(Number(week))?' (Deload)':''}`}
function formatProgramDate(value){if(!validDateString(value))return 'Starts with first saved workout';return `Started ${new Date(value+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`}
function recalculateProgramWeeks(){delete state.data.startDate;delete state.data.week;(state.data.history||[]).forEach(workout=>{workout.programWeek=weekForDate(workout.date)})}
function allEntries(name){return state.data.history.flatMap(w=>w.exercises.filter(e=>e.name===name).map(e=>({...e,date:w.date,type:w.type,programWeek:w.programWeek||null})))}
function lastEntry(name){const a=allEntries(name);return a[a.length-1]||null}
function e1rm(weight,reps){return weight&&reps?Math.round(weight*(1+reps/30)):0}
function bestE1RM(name){return Math.max(0,...allEntries(name).flatMap(e=>e.reps.map(r=>e1rm(e.weight,r))))}
function mainWeights(){return ['Bench Press','Back Squat','Deadlift','Standing OHP']}
function renderHome(){const week=currentProgramWeek();$('#weekNumber').textContent=weekLabel(week);$('#programStartText').textContent=formatProgramDate(programStartDate());$('#dashboardGrid').innerHTML=mainWeights().map(n=>{const l=lastEntry(n);return`<div class="metric-card"><span>${n}</span><strong>${l?l.weight+' lb':'--'}</strong><span>${l?l.reps.join('/'):'No entry yet'}</span></div>`}).join('');const el=$('#workoutButtons');el.innerHTML='';Object.entries(PROGRAM).forEach(([n,items])=>{const b=document.createElement('button');b.className='workout-choice';b.innerHTML=`<strong>${n}</strong><span>${items.length} exercises</span>`;b.onclick=()=>openWorkout(n);el.appendChild(b)})}
function openWorkout(name){state.selected=name;$('#workoutTitle').textContent=name;$('#workoutDate').value=new Date().toISOString().slice(0,10);const wrap=$('#exerciseList');wrap.innerHTML='';PROGRAM[name].forEach((ex,idx)=>{const last=lastEntry(ex.name),best=bestE1RM(ex.name);const card=document.createElement('article');card.className='exercise-card';card.dataset.idx=idx;card.innerHTML=`<div class="exercise-head"><div><h3>${ex.name}${best?'<span class="pr-badge">e1RM '+best+'</span>':''}</h3><span class="goal">${ex.sets} × ${ex.min===ex.max?ex.max:ex.min+'-'+ex.max}</span></div><div class="weight-wrap"><label>Weight</label><div class="weight-controls"><button type="button" class="weight-adjust" data-adjust="-5" aria-label="Decrease weight by 5 pounds">-5</button><input class="weight-input" type="number" step="5" inputmode="decimal" value="${last?.weight??''}" placeholder="lb"><button type="button" class="weight-adjust" data-adjust="5" aria-label="Increase weight by 5 pounds">+5</button></div></div></div>${last?`<div class="last-line">Last: ${last.weight} lb × ${last.reps.join(' / ')} on ${last.date}</div>`:''}<div class="sets-label">Sets and reps</div><div class="sets-grid" style="--sets:${ex.sets}">${Array.from({length:ex.sets},(_,i)=>`<div class="set-cell"><label>S${i+1}</label><input inputmode="numeric" maxlength="3" aria-label="${ex.name} set ${i+1} reps"></div>`).join('')}</div><div class="recommendation hold">Enter all sets to see progression</div>`;wrap.appendChild(card);card.querySelectorAll('.weight-adjust').forEach(button=>button.addEventListener('click',()=>{const input=card.querySelector('.weight-input');input.value=(Number(input.value)||0)+Number(button.dataset.adjust);updateRecommendation(card,ex)}));card.querySelectorAll('.set-cell input').forEach(i=>i.addEventListener('input',()=>updateRecommendation(card,ex)))});showView('workout')}
function updateRecommendation(card,ex){const reps=[...card.querySelectorAll('.set-cell input')].map(i=>Number(i.value)),out=card.querySelector('.recommendation');if(reps.some(r=>!r)){out.className='recommendation hold';out.textContent='Enter all sets to see progression';return}const earned=reps.every(r=>r>=ex.max),weight=Number(card.querySelector('.weight-input').value)||0;out.className='recommendation '+(earned?'increase':'hold');out.textContent=earned?(ex.step?`Increase next time to ${weight+ex.step} lb`:'Top range completed'):'Keep the same weight next time'}
function saveWorkout(){const date=$('#workoutDate').value;if(!validDateString(date)){toast('Choose a valid workout date');return}const exercises=PROGRAM[state.selected].map((ex,idx)=>{const card=$(`.exercise-card[data-idx="${idx}"]`);return{name:ex.name,weight:Number(card.querySelector('.weight-input').value)||0,reps:[...card.querySelectorAll('.set-cell input')].map(i=>Number(i.value)||0),goal:`${ex.sets} x ${ex.min}-${ex.max}`}});if(exercises.some(e=>e.reps.some(r=>r===0))){toast('Enter reps for every set');return}state.data.history.push({id:Date.now(),date,type:state.selected,programWeek:1,exercises});recalculateProgramWeeks();const savedWorkout=state.data.history[state.data.history.length-1];persist();renderHome();toast(`Workout saved · ${weekLabel(savedWorkout.programWeek)}`);showView('history')}
function renderHistory(){
 const el=$('#historyList');
 el.innerHTML=state.data.history.length?state.data.history.slice().reverse().map(w=>`<details class="card history-item"><summary><div class="history-summary-row"><strong>${w.type}</strong><span>${w.date}${[6,12].includes(Number(w.programWeek))?' (Deload)':''}</span><button class="trash-btn" data-delete-id="${w.id}" aria-label="Delete ${w.type} on ${w.date}" title="Delete workout">🗑</button></div></summary><div class="history-details">${w.exercises.map(e=>{const best=Math.max(...e.reps.map(r=>e1rm(e.weight,r)));return`<div class="history-exercise"><strong>${e.name}</strong><span>${e.weight||'Bodyweight'}${e.weight?' lb':''}</span><small>Reps: ${e.reps.join(' / ')}${best?' · e1RM '+best:''}</small></div>`}).join('')}</div></details>`).join(''):'<div class="card"><h3>No workouts saved yet</h3><p>Complete a workout and it will appear here.</p></div>';
 el.querySelectorAll('.trash-btn').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();deleteWorkout(Number(button.dataset.deleteId))}));
 renderExerciseSelect()
}
function deleteWorkout(id){
 const workout=state.data.history.find(item=>Number(item.id)===Number(id));
 if(!workout)return;
 if(!confirm(`Delete ${workout.type} from ${workout.date}?`))return;
 state.data.history=state.data.history.filter(item=>Number(item.id)!==Number(id));
 recalculateProgramWeeks();persist();renderHome();renderHistory();toast('Workout deleted')
}
function exerciseNames(){return [...new Set(Object.values(PROGRAM).flat().map(e=>e.name))]}
function renderExerciseSelect(){const s=$('#exerciseSelect'),old=s.value;s.innerHTML=exerciseNames().map(n=>`<option>${n}</option>`).join('');if(old)s.value=old;renderExerciseHistory()}
function renderExerciseHistory(){const name=$('#exerciseSelect').value,entries=allEntries(name),best=bestE1RM(name),last=entries.at(-1);$('#exerciseStats').innerHTML=`<div class="stat"><span>Last load</span><strong>${last?last.weight+' lb':'--'}</strong></div><div class="stat"><span>Best e1RM</span><strong>${best||'--'}</strong></div><div class="stat"><span>Sessions</span><strong>${entries.length}</strong></div>`;$('#exerciseHistoryList').innerHTML=entries.slice().reverse().map(e=>`<div class="card exercise-log"><strong>${e.date}</strong><span>${e.weight} lb · ${e.reps.join('/')}</span><span class="e1rm">e1RM ${Math.max(...e.reps.map(r=>e1rm(e.weight,r)))}</span></div>`).join('')||'<div class="card"><p>No entries yet.</p></div>';drawChart(entries)}
function drawChart(entries){
 const canvas=$('#progressChart'),ctx=canvas.getContext('2d'),dpr=window.devicePixelRatio||1,w=canvas.clientWidth||700,h=300;
 canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
 const values=entries.map(entry=>Math.max(...entry.reps.map(reps=>e1rm(entry.weight,reps))));
 const styles=getComputedStyle(document.body),muted=styles.getPropertyValue('--muted').trim()||'#657482',grid=styles.getPropertyValue('--line').trim()||'#d8e0e6';
 const margin={left:54,right:12,top:18,bottom:78},plotWidth=w-66,plotHeight=h-96;
 ctx.font='11px system-ui';ctx.fillStyle=muted;ctx.strokeStyle=grid;ctx.lineWidth=1;ctx.textBaseline='middle';
 if(!values.length){ctx.textAlign='center';ctx.fillText('No data yet',w/2,h/2);return}
 let minimum=Math.min(...values),maximum=Math.max(...values);const padding=Math.max(5,Math.ceil((maximum-minimum||10)*.15));minimum=Math.floor((minimum-padding)/5)*5;maximum=Math.ceil((maximum+padding)/5)*5;if(maximum===minimum)maximum=minimum+10;
 const tickCount=5;
 for(let i=0;i<tickCount;i++){const value=Math.round(maximum-i*(maximum-minimum)/(tickCount-1)),y=margin.top+i*plotHeight/(tickCount-1);ctx.beginPath();ctx.moveTo(margin.left,y);ctx.lineTo(w-margin.right,y);ctx.stroke();ctx.textAlign='right';ctx.fillText(String(value),margin.left-7,y)}
 ctx.save();ctx.translate(14,margin.top+plotHeight/2);ctx.rotate(-Math.PI/2);ctx.textAlign='center';ctx.fillText('Estimated 1RM (lb)',0,0);ctx.restore();
 const pointX=index=>margin.left+(values.length===1?plotWidth/2:index*plotWidth/(values.length-1));
 const pointY=value=>margin.top+(maximum-value)*plotHeight/(maximum-minimum);
 ctx.strokeStyle='#2b75a9';ctx.lineWidth=3;ctx.beginPath();values.forEach((value,index)=>index?ctx.lineTo(pointX(index),pointY(value)):ctx.moveTo(pointX(index),pointY(value)));ctx.stroke();
 ctx.fillStyle='#17365d';values.forEach((value,index)=>{ctx.beginPath();ctx.arc(pointX(index),pointY(value),4,0,Math.PI*2);ctx.fill()});
 const maximumLabels=Math.max(2,Math.floor(plotWidth/80)),stride=Math.max(1,Math.ceil(entries.length/maximumLabels));ctx.fillStyle=muted;ctx.font='10px system-ui';ctx.textAlign='right';
 entries.forEach((entry,index)=>{if(index%stride&&index!==entries.length-1)return;const parsed=new Date(entry.date+'T00:00:00'),date=isNaN(parsed)?entry.date:parsed.toLocaleDateString(undefined,{month:'short',day:'numeric'}),label=date+([6,12].includes(Number(entry.programWeek))?' (Deload)':'');ctx.save();ctx.translate(pointX(index),margin.top+plotHeight+11);ctx.rotate(-Math.PI/4);ctx.fillText(label,0,0);ctx.restore()});
 ctx.textAlign='center';ctx.fillText('Workout date',margin.left+plotWidth/2,h-8)
}
function exportData(){const blob=new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='strength-tracker-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(file){const r=new FileReader();r.onload=()=>{try{state.data=JSON.parse(r.result);recalculateProgramWeeks();persist();renderHome();renderHistory();toast('Backup imported')}catch{toast('That backup file is invalid')}};r.readAsText(file)}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go="home"]').forEach(b=>b.onclick=()=>showView('home'));$$('[data-history]').forEach(b=>b.onclick=()=>{$$('[data-history]').forEach(x=>x.classList.toggle('active',x===b));$('#workoutHistoryPanel').classList.toggle('hidden',b.dataset.history!=='workouts');$('#exerciseHistoryPanel').classList.toggle('hidden',b.dataset.history!=='exercises');if(b.dataset.history==='exercises')renderExerciseHistory()});$('#exerciseSelect').onchange=renderExerciseHistory;$('#saveWorkoutBtn').onclick=saveWorkout;$('#exportBtn').onclick=exportData;$('#importInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('strengthDark',document.body.classList.contains('dark'))};if(localStorage.getItem('strengthDark')==='true')document.body.classList.add('dark');recalculateProgramWeeks();persist();renderHome();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');