const DEFAULT_EXERCISES=[
 {id:'bench-press',name:'Bench Press',defaultSets:5,reps:5,step:5},
 {id:'weighted-pull-ups',name:'Weighted Pull-Ups',defaultSets:5,reps:5,step:5},
 {id:'standing-ohp',name:'Standing OHP',defaultSets:4,reps:5,step:5},
 {id:'barbell-row',name:'Barbell Row',defaultSets:4,reps:8,step:5},
 {id:'dips',name:'Dips',defaultSets:4,reps:8,step:5},
 {id:'hammer-curl',name:'Hammer Curl',defaultSets:3,reps:10,step:5},
 {id:'back-squat',name:'Back Squat',defaultSets:5,reps:5,step:10},
 {id:'deadlift',name:'Deadlift',defaultSets:3,reps:5,step:10},
 {id:'bulgarian-split-squat',name:'Bulgarian Split Squat',defaultSets:3,reps:8,step:5},
 {id:'leg-curl',name:'Leg Curl',defaultSets:3,reps:10,step:5},
 {id:'pinky-crushers',name:'Pinky Crushers',defaultSets:3,reps:12,step:5},
 {id:'weighted-back-extension',name:'Weighted Back Extension',defaultSets:3,reps:12,step:5},
 {id:'incline-db-bench',name:'Incline DB Bench',defaultSets:5,reps:10,step:5},
 {id:'chest-supported-row',name:'Chest Supported Row',defaultSets:4,reps:10,step:5},
 {id:'seated-db-press',name:'Seated DB Press',defaultSets:4,reps:10,step:5},
 {id:'lat-pulldown',name:'Lat Pulldown',defaultSets:3,reps:12,step:5},
 {id:'lateral-raise',name:'Lateral Raise',defaultSets:4,reps:15,step:5},
 {id:'triceps-pushdown',name:'Triceps Pushdown',defaultSets:3,reps:15,step:5},
 {id:'ez-bar-curl',name:'EZ Bar Curl',defaultSets:3,reps:12,step:5},
 {id:'front-squat',name:'Front Squat',defaultSets:4,reps:8,step:10},
 {id:'romanian-deadlift',name:'Romanian Deadlift',defaultSets:4,reps:8,step:10},
 {id:'leg-extension',name:'Leg Extension',defaultSets:4,reps:15,step:5},
 {id:'leg-press',name:'Leg Press',defaultSets:3,reps:15,step:10},
 {id:'calf-raise',name:'Calf Raise',defaultSets:4,reps:15,step:5},
 {id:'ab-wheel',name:'Ab Wheel',defaultSets:4,reps:10,step:0}
];
const DEFAULT_WORKOUTS=[
 {id:'upper-strength',name:'Upper Strength',day:'Monday',exerciseIds:['bench-press','weighted-pull-ups','standing-ohp','barbell-row','dips','hammer-curl']},
 {id:'lower-strength',name:'Lower Strength',day:'Tuesday',exerciseIds:['back-squat','deadlift','bulgarian-split-squat','leg-curl','pinky-crushers','weighted-back-extension']},
 {id:'upper-volume',name:'Upper Volume',day:'Thursday',exerciseIds:['incline-db-bench','chest-supported-row','seated-db-press','lat-pulldown','lateral-raise','triceps-pushdown','ez-bar-curl']},
 {id:'lower-volume',name:'Lower Volume',day:'Friday',exerciseIds:['front-squat','romanian-deadlift','leg-extension','leg-press','calf-raise','ab-wheel']}
];
const STORE='seanStrengthTrackerV10';
let raw=localStorage.getItem(STORE)||localStorage.getItem('seanStrengthTrackerV9')||localStorage.getItem('seanStrengthTrackerV8')||localStorage.getItem('seanStrengthTrackerV6_1')||localStorage.getItem('seanStrengthTrackerV6')||localStorage.getItem('seanStrengthTrackerV5')||localStorage.getItem('seanStrengthTrackerV4')||localStorage.getItem('seanStrengthTrackerV2')||localStorage.getItem('seanStrengthTrackerV1');
const parsed=raw?JSON.parse(raw):null;
const state={selected:null,data:parsed&&parsed.exercises&&parsed.workouts?parsed:{history:parsed?.history||[],startDate:null,exercises:DEFAULT_EXERCISES.slice(),workouts:DEFAULT_WORKOUTS.slice()}};
if(!state.data.exercises)state.data.exercises=DEFAULT_EXERCISES.slice();
if(!state.data.workouts)state.data.workouts=DEFAULT_WORKOUTS.slice();
let workoutTimerInterval=null,workoutStartTime=null,restTimerInterval=null,restStartTime=null,restElapsedBeforePause=0,restRunning=false;
let workoutDurationStart=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function persist(){localStorage.setItem(STORE,JSON.stringify(state.data));}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function showView(n){document.body.classList.toggle('workout-mode',n==='workout');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+n+'View').classList.add('active');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===n));if(n==='history')renderHistory();if(n==='exercises')renderExerciseLibrary();if(n==='templates')renderTemplates();scrollTo(0,0)}
function validDateString(value){return /^\d{4}-\d{2}-\d{2}$/.test(value||'')&&!Number.isNaN(new Date(value+'T00:00:00').getTime())}
function programStartDate(){const dates=(state.data.history||[]).map(w=>w.date).filter(validDateString).sort();return dates[0]||null}
function weekForDate(value){const start=programStartDate();if(!start||!validDateString(value))return 1;const startDate=new Date(start+'T00:00:00'),target=new Date(value+'T00:00:00');const days=Math.floor((target-startDate)/86400000);return Math.max(1,Math.floor(days/7)+1)}
function currentProgramWeek(){return weekForDate(new Date().toISOString().slice(0,10))}
function weekLabel(week){return `Week ${week}${[6,12].includes(Number(week))?' (Deload)':''}`}
function formatProgramDate(value){if(!validDateString(value))return 'Starts with first saved workout';return `Started ${new Date(value+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`}
function recalculateProgramWeeks(){delete state.data.startDate;delete state.data.week;(state.data.history||[]).forEach(workout=>{workout.programWeek=weekForDate(workout.date)})}
function allEntries(name){return state.data.history.flatMap(w=>w.exercises.filter(e=>e.name===name).map(e=>({...e,date:w.date,type:w.type,programWeek:w.programWeek||null})))}
function lastEntry(name){const a=allEntries(name);return a[a.length-1]||null}
function e1rm(weight,reps){return weight&&reps?Math.round(weight*(1+reps/30)):0}
function bestE1RM(name){return Math.max(0,...allEntries(name).flatMap(e=>e.reps.map(r=>e1rm(e.weight,r))))}
function formatDuration(ms){const total=Math.max(0,Math.floor(ms/1000)),h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function mainWeights(){return ['Bench Press','Back Squat','Deadlift','Standing OHP']}
function exerciseById(id){return state.data.exercises.find(e=>e.id===id)||null}
function workoutById(id){return state.data.workouts.find(w=>w.id===id)||null}
function exerciseNameList(){return [...new Set(state.data.exercises.map(e=>e.name))]}
function clampSets(v){return Math.max(1,Math.min(10,Number(v)||1))}
function renderHome(){const week=currentProgramWeek();$('#weekNumber').textContent=weekLabel(week);$('#programStartText').textContent=formatProgramDate(programStartDate());$('#dashboardGrid').innerHTML=mainWeights().map(n=>{const l=lastEntry(n);return`<div class="metric-card"><span>${n}</span><strong>${l?l.weight+' lb':'--'}</strong><span>${l?l.reps.join('/'):'No entry yet'}</span></div>`}).join('');const el=$('#workoutButtons');el.innerHTML='';state.data.workouts.forEach(w=>{const b=document.createElement('button');b.className='workout-choice';b.innerHTML=`<strong>${w.name}</strong><span>${w.exerciseIds.length} exercises</span><span class="workout-day">${w.day}</span>`;b.onclick=()=>openWorkout(w.id);el.appendChild(b)})}
function openWorkout(workoutId){const workout=workoutById(workoutId)||state.data.workouts[0];if(!workout)return;document.body.classList.add('workout-mode');state.selected=workout.id;$('#workoutTitle').textContent=workout.name;$('#workoutDate').value=new Date().toISOString().slice(0,10);resetRestTimer();startWorkoutTimer();workoutDurationStart=Date.now();renderWorkoutEditor(workout);showView('workout');updateRestControls()}
function renderWorkoutEditor(workout){const wrap=$('#exerciseList');wrap.innerHTML='';workout.exerciseIds.forEach((exerciseId,idx)=>{const ex=exerciseById(exerciseId);if(!ex)return;const last=lastEntry(ex.name),best=bestE1RM(ex.name);const reps=Number(ex.reps)||0;const card=document.createElement('article');card.className='exercise-card';card.dataset.idx=idx;card.innerHTML=`<div class="exercise-head"><div><h3>${ex.name}${best?'<span class="pr-badge">e1RM '+best+'</span>':''}</h3><span class="goal">${ex.defaultSets} × ${reps}</span></div><div class="weight-wrap"><label>Weight</label><div class="weight-controls"><button type="button" class="weight-adjust" data-adjust="-5" aria-label="Decrease weight by 5 pounds">-5</button><input class="weight-input" type="number" step="5" inputmode="decimal" value="${last?.weight??''}" placeholder="lb"><button type="button" class="weight-adjust" data-adjust="5" aria-label="Increase weight by 5 pounds">+5</button></div></div></div>${last?`<div class="last-line">Last: ${last.weight} lb × ${last.reps.join(' / ')} on ${last.date}</div>`:''}<div class="sets-label">Sets and reps</div><div class="sets-grid" style="--sets:${ex.defaultSets}">${Array.from({length:ex.defaultSets},(_,i)=>`<div class="set-cell"><label>S${i+1}</label><input inputmode="numeric" maxlength="3" aria-label="${ex.name} set ${i+1} reps"></div>`).join('')}</div><div class="recommendation hold">Enter all sets to see progression</div>`;wrap.appendChild(card);card.querySelectorAll('.weight-adjust').forEach(button=>button.addEventListener('click',()=>{const input=card.querySelector('.weight-input');input.value=(Number(input.value)||0)+Number(button.dataset.adjust);updateRecommendation(card,ex)}));card.querySelectorAll('.set-cell input').forEach(i=>i.addEventListener('input',()=>updateRecommendation(card,ex)))});bindWorkoutTemplateButtons(workout)}
function updateRecommendation(card,ex){const reps=[...card.querySelectorAll('.set-cell input')].map(i=>Number(i.value)),out=card.querySelector('.recommendation');if(reps.some(r=>!r)){out.className='recommendation hold';out.textContent='Enter all sets to see progression';return}const earned=reps.every(r=>r>=Number(ex.reps)||0),weight=Number(card.querySelector('.weight-input').value)||0;out.className='recommendation '+(earned?'increase':'hold');out.textContent=earned?(ex.step?`Increase next time to ${weight+ex.step} lb`:'Top range completed'):'Keep the same weight next time'}
function updateWorkoutTimerDisplay(){if(!workoutStartTime)return;$('#workoutElapsed').textContent=formatDuration(Date.now()-workoutStartTime)}
function startWorkoutTimer(){stopWorkoutTimer();workoutStartTime=Date.now();updateWorkoutTimerDisplay();workoutTimerInterval=setInterval(updateWorkoutTimerDisplay,1000)}
function stopWorkoutTimer(){clearInterval(workoutTimerInterval);workoutTimerInterval=null;workoutStartTime=null;const el=$('#workoutElapsed');if(el)el.textContent='00:00'}
function updateRestControls(){const btn=$('#restStartBtn');if(!btn)return;btn.textContent=restRunning?'Stop':'Start';btn.classList.toggle('stop',restRunning);btn.classList.toggle('start',!restRunning)}
function updateRestDisplay(){const elapsed=restElapsedBeforePause+(restRunning?Date.now()-restStartTime:0);$('#restElapsed').textContent=formatDuration(elapsed);updateRestControls()}
function startRestTimer(){if(restRunning){stopRestTimer();return}restRunning=true;restStartTime=Date.now();clearInterval(restTimerInterval);restTimerInterval=setInterval(updateRestDisplay,1000);updateRestDisplay()}
function stopRestTimer(){if(!restRunning)return;restElapsedBeforePause+=Date.now()-restStartTime;restRunning=false;clearInterval(restTimerInterval);restTimerInterval=null;updateRestDisplay()}
function resetRestTimer(){clearInterval(restTimerInterval);restTimerInterval=null;restRunning=false;restStartTime=null;restElapsedBeforePause=0;const el=$('#restElapsed');if(el)el.textContent='00:00';updateRestControls()}
function saveWorkout(){const date=$('#workoutDate').value;if(!validDateString(date)){toast('Choose a valid workout date');return}const workout=workoutById(state.selected);const durationMs=workoutDurationStart?Date.now()-workoutDurationStart:null;const exercises=workout?.exerciseIds.map((exerciseId,idx)=>{const ex=exerciseById(exerciseId);const card=$(`.exercise-card[data-idx="${idx}"]`);return{name:ex.name,weight:Number(card.querySelector('.weight-input').value)||0,reps:[...card.querySelectorAll('.set-cell input')].map(i=>Number(i.value)||0),goal:`${ex.defaultSets} x ${ex.reps||0}`}})||[];if(exercises.some(e=>e.reps.some(r=>r===0))){toast('Enter reps for every set');return}state.data.history.push({id:Date.now(),date,type:workout.name,programWeek:1,durationMs,exercises});recalculateProgramWeeks();const savedWorkout=state.data.history[state.data.history.length-1];persist();stopWorkoutTimer();resetRestTimer();workoutDurationStart=null;document.body.classList.remove('workout-mode');renderHome();toast(`Workout saved · ${weekLabel(savedWorkout.programWeek)}`);showView('history')}
function renderHistory(){const el=$('#historyList');el.innerHTML=state.data.history.length?state.data.history.slice().reverse().map(w=>{const timeText=typeof w.durationMs==='number'&&w.durationMs>0?formatDuration(w.durationMs):'--';return`<details class="card history-item"><summary><div class="history-summary-row"><div class="history-left"><strong class="history-workout-name">${w.type}</strong><span class="history-time" style="display:inline-block;margin-left:18px;min-width:64px;">${timeText}</span></div><div class="history-right"><span class="history-date">${w.date}${[6,12].includes(Number(w.programWeek))?' (Deload)':''}</span><button class="trash-btn" data-delete-id="${w.id}" aria-label="Delete ${w.type} on ${w.date}" title="Delete workout">🗑</button></div></div></summary><div class="history-details">${w.exercises.map(e=>{const best=Math.max(...e.reps.map(r=>e1rm(e.weight,r)));return`<div class="history-exercise"><strong>${e.name}</strong><span>${e.weight||'Bodyweight'}${e.weight?' lb':''}</span><small>Reps: ${e.reps.join(' / ')}${best?' · e1RM '+best:''}</small></div>`}).join('')}</div></details>`}).join(''):'<div class="card"><h3>No workouts saved yet</h3><p>Complete a workout and it will appear here.</p></div>';el.querySelectorAll('.trash-btn').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();deleteWorkout(Number(button.dataset.deleteId))}));renderExerciseSelect()}
function deleteWorkout(id){const workout=state.data.history.find(item=>Number(item.id)===Number(id));if(!workout)return;if(!confirm(`Delete ${workout.type} from ${workout.date}?`))return;state.data.history=state.data.history.filter(item=>Number(item.id)!==Number(id));recalculateProgramWeeks();persist();renderHome();renderHistory();toast('Workout deleted')}
function renderExerciseSelect(){const s=$('#exerciseSelect'),old=s.value;s.innerHTML=exerciseNameList().map(n=>`<option>${n}</option>`).join('');if(old)s.value=old;renderExerciseHistory()}
function renderExerciseHistory(){const name=$('#exerciseSelect').value,entries=allEntries(name),best=bestE1RM(name),last=entries.at(-1);$('#exerciseStats').innerHTML=`<div class="stat"><span>Last load</span><strong>${last?last.weight+' lb':'--'}</strong></div><div class="stat"><span>Best e1RM</span><strong>${best||'--'}</strong></div><div class="stat"><span>Sessions</span><strong>${entries.length}</strong></div>`;$('#exerciseHistoryList').innerHTML=entries.slice().reverse().map(e=>`<div class="card exercise-log"><strong>${e.date}</strong><span>${e.weight} lb · ${e.reps.join('/')}</span><span class="e1rm">e1RM ${Math.max(...e.reps.map(r=>e1rm(e.weight,r)))}</span></div>`).join('')||'<div class="card"><p>No entries yet.</p></div>';drawChart(entries)}
function renderExerciseLibrary(){const el=$('#exerciseLibraryList');el.innerHTML=`<div class="exercise-library-grid">${state.data.exercises.map(ex=>`<div class="exercise-item" data-id="${ex.id}"><div class="exercise-item-head"><strong>${ex.name}</strong></div><div class="exercise-meta"><label>Name<input data-field="name" value="${ex.name}"></label><label>Sets<input data-field="defaultSets" type="number" value="${clampSets(ex.defaultSets)}" max="10"></label><label>Reps<input data-field="reps" type="number" value="${ex.reps}"></label></div><div class="exercise-actions"><button class="secondary" data-save-exercise="${ex.id}">Save</button><button class="danger" data-delete-exercise="${ex.id}">Delete</button></div></div>`).join('')}</div>`;el.querySelectorAll('[data-save-exercise]').forEach(btn=>btn.onclick=()=>saveExercise(btn.dataset.saveExercise));el.querySelectorAll('[data-delete-exercise]').forEach(btn=>btn.onclick=()=>deleteExercise(btn.dataset.deleteExercise))}
function addExercise(){const id=`exercise-${Date.now()}`;state.data.exercises.push({id,name:'New Exercise',defaultSets:3,reps:10,step:5});persist();renderExerciseLibrary();renderExerciseSelect();renderHome();requestAnimationFrame(()=>{const card=$(`.exercise-item[data-id="${id}"]`);card?.scrollIntoView({behavior:'smooth',block:'center'})})}
function saveExercise(id){const card=$(`.exercise-item[data-id="${id}"]`);const ex=state.data.exercises.find(x=>x.id===id);if(!card||!ex)return;ex.name=card.querySelector('[data-field="name"]').value.trim()||'Unnamed Exercise';ex.defaultSets=clampSets(card.querySelector('[data-field="defaultSets"]').value);ex.reps=Number(card.querySelector('[data-field="reps"]').value)||0;persist();renderExerciseLibrary();renderExerciseSelect();renderHome();toast('Exercise saved')}
function deleteExercise(id){state.data.exercises=state.data.exercises.filter(x=>x.id!==id);state.data.workouts.forEach(w=>w.exerciseIds=w.exerciseIds.filter(exId=>exId!==id));persist();renderExerciseLibrary();renderHome();renderExerciseSelect();toast('Exercise deleted')}
function renderTemplates(){const el=$('#templateList');el.innerHTML=`<div class="template-list">${state.data.workouts.map(w=>{const options=exerciseNameList().map(n=>`<option>${n}</option>`).join('');return`<div class="template-card" data-template-id="${w.id}"><div class="template-head"><strong>${w.name}</strong><button class="secondary" data-save-template="${w.id}">Save</button></div><div class="template-meta"><label>Name<input data-field="template-name" value="${w.name}"></label><label>Day<select data-field="template-day"><option${w.day==='Monday'?' selected':''}>Monday</option><option${w.day==='Tuesday'?' selected':''}>Tuesday</option><option${w.day==='Wednesday'?' selected':''}>Wednesday</option><option${w.day==='Thursday'?' selected':''}>Thursday</option><option${w.day==='Friday'?' selected':''}>Friday</option><option${w.day==='Saturday'?' selected':''}>Saturday</option><option${w.day==='Sunday'?' selected':''}>Sunday</option></select></label></div><div class="template-exercises">${w.exerciseIds.map((id,idx)=>{const ex=exerciseById(id);return`<div class="template-exercise" data-exercise-index="${idx}"><strong>${ex?ex.name:'Missing exercise'}</strong><button class="move-btn" data-move-up="${idx}">↑</button><button class="move-btn" data-move-down="${idx}">↓</button><button class="remove-btn" data-remove-exercise="${idx}">Remove</button></div>`}).join('')}</div><div class="template-add-row"><select data-add-select>${options}</select><button class="primary" data-add-exercise-to-template="${w.id}">Add exercise</button></div></div>`}).join('')}</div>`;el.querySelectorAll('[data-save-template]').forEach(btn=>btn.onclick=()=>saveTemplate(btn.dataset.saveTemplate));el.querySelectorAll('[data-remove-exercise]').forEach(btn=>btn.onclick=()=>removeExerciseFromTemplate(btn.closest('.template-card').dataset.templateId,Number(btn.dataset.removeExercise)));el.querySelectorAll('[data-move-up]').forEach(btn=>btn.onclick=()=>moveExerciseInTemplate(btn.closest('.template-card').dataset.templateId,Number(btn.dataset.moveUp),-1));el.querySelectorAll('[data-move-down]').forEach(btn=>btn.onclick=()=>moveExerciseInTemplate(btn.closest('.template-card').dataset.templateId,Number(btn.dataset.moveDown),1));el.querySelectorAll('[data-add-exercise-to-template]').forEach(btn=>btn.onclick=()=>addExerciseToTemplate(btn.dataset.addExerciseToTemplate))}
function saveTemplate(id){const card=$(`.template-card[data-template-id="${id}"]`);const w=workoutById(id);if(!card||!w)return;w.name=card.querySelector('[data-field="template-name"]').value.trim()||w.name;w.day=card.querySelector('[data-field="template-day"]').value;persist();renderHome();renderTemplates();toast('Template saved')}
function addExerciseToTemplate(id){const card=$(`.template-card[data-template-id="${id}"]`);const w=workoutById(id);if(!card||!w)return;const selected=card.querySelector('[data-add-select]').value;const ex=state.data.exercises.find(e=>e.name===selected);if(!ex){toast('Pick an exercise');return}w.exerciseIds.push(ex.id);persist();renderTemplates();renderHome();toast('Exercise added')}
function removeExerciseFromTemplate(templateId,index){const w=workoutById(templateId);if(!w)return;w.exerciseIds.splice(index,1);persist();renderTemplates();renderHome();toast('Exercise removed')}
function moveExerciseInTemplate(templateId,index,direction){const w=workoutById(templateId);if(!w)return;const next=index+direction;if(next<0||next>=w.exerciseIds.length)return;[w.exerciseIds[index],w.exerciseIds[next]]=[w.exerciseIds[next],w.exerciseIds[index]];persist();renderTemplates();renderHome()}
function bindWorkoutTemplateButtons(workout){}
function drawChart(entries){const canvas=$('#progressChart'),ctx=canvas.getContext('2d'),dpr=window.devicePixelRatio||1,w=canvas.clientWidth||700,h=300;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const values=entries.map(entry=>Math.max(...entry.reps.map(reps=>e1rm(entry.weight,reps))));const styles=getComputedStyle(document.body),muted=styles.getPropertyValue('--muted').trim()||'#657482',grid=styles.getPropertyValue('--line').trim()||'#d8e0e6';const margin={left:54,right:12,top:18,bottom:78},plotWidth=w-66,plotHeight=h-96;ctx.font='11px system-ui';ctx.fillStyle=muted;ctx.strokeStyle=grid;ctx.lineWidth=1;ctx.textBaseline='middle';if(!values.length){ctx.textAlign='center';ctx.fillText('No data yet',w/2,h/2);return}let minimum=Math.min(...values),maximum=Math.max(...values);const padding=Math.max(5,Math.ceil((maximum-minimum||10)*.15));minimum=Math.floor((minimum-padding)/5)*5;maximum=Math.ceil((maximum+padding)/5)*5;if(maximum===minimum)maximum=minimum+10;const tickCount=5;for(let i=0;i<tickCount;i++){const value=Math.round(maximum-i*(maximum-minimum)/(tickCount-1)),y=margin.top+i*plotHeight/(tickCount-1);ctx.beginPath();ctx.moveTo(margin.left,y);ctx.lineTo(w-margin.right,y);ctx.stroke();ctx.textAlign='right';ctx.fillText(String(value),margin.left-7,y)}ctx.save();ctx.translate(14,margin.top+plotHeight/2);ctx.rotate(-Math.PI/2);ctx.textAlign='center';ctx.fillText('Estimated 1RM (lb)',0,0);ctx.restore();const pointX=index=>margin.left+(values.length===1?plotWidth/2:index*plotWidth/(values.length-1));const pointY=value=>margin.top+(maximum-value)*plotHeight/(maximum-minimum);ctx.strokeStyle='#2b75a9';ctx.lineWidth=3;ctx.beginPath();values.forEach((value,index)=>index?ctx.lineTo(pointX(index),pointY(value)):ctx.moveTo(pointX(index),pointY(value)));ctx.stroke();ctx.fillStyle='#17365d';values.forEach((value,index)=>{ctx.beginPath();ctx.arc(pointX(index),pointY(value),4,0,Math.PI*2);ctx.fill()});const maximumLabels=Math.max(2,Math.floor(plotWidth/80)),stride=Math.max(1,Math.ceil(entries.length/maximumLabels));ctx.fillStyle=muted;ctx.font='10px system-ui';ctx.textAlign='right';entries.forEach((entry,index)=>{if(index%stride&&index!==entries.length-1)return;const parsed=new Date(entry.date+'T00:00:00'),date=isNaN(parsed)?entry.date:parsed.toLocaleDateString(undefined,{month:'short',day:'numeric'}),label=date+([6,12].includes(Number(entry.programWeek))?' (Deload)':'');ctx.save();ctx.translate(pointX(index),margin.top+plotHeight+11);ctx.rotate(-Math.PI/4);ctx.fillText(label,0,0);ctx.restore()});ctx.textAlign='center';ctx.fillText('Workout date',margin.left+plotWidth/2,h-8)}
function exportData(){const blob=new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='strength-tracker-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(file){const r=new FileReader();r.onload=()=>{try{state.data=JSON.parse(r.result);if(!state.data.exercises)state.data.exercises=DEFAULT_EXERCISES.slice();if(!state.data.workouts)state.data.workouts=DEFAULT_WORKOUTS.slice();recalculateProgramWeeks();persist();renderHome();renderHistory();renderExerciseLibrary();renderTemplates();toast('Backup imported')}catch{toast('That backup file is invalid')}};r.readAsText(file)}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go="home"]').forEach(b=>b.onclick=()=>{stopWorkoutTimer();resetRestTimer();showView('home')});$$('[data-history]').forEach(b=>b.onclick=()=>{$$('[data-history]').forEach(x=>x.classList.toggle('active',x===b));$('#workoutHistoryPanel').classList.toggle('hidden',b.dataset.history!=='workouts');$('#exerciseHistoryPanel').classList.toggle('hidden',b.dataset.history!=='exercises');if(b.dataset.history==='exercises')renderExerciseHistory()});$('#exerciseSelect').onchange=renderExerciseHistory;$('#saveWorkoutBtn').onclick=saveWorkout;$('#restStartBtn').onclick=startRestTimer;$('#restResetBtn').onclick=resetRestTimer;$('#addExerciseBtn').onclick=addExercise;$('#exportBtn').onclick=exportData;$('#importInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('strengthDark',document.body.classList.contains('dark'))};if(localStorage.getItem('strengthDark')==='true')document.body.classList.add('dark');recalculateProgramWeeks();persist();renderHome();renderExerciseLibrary();renderTemplates();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');